# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LtIseAETzHTOexgtG-m0-vqsqETC5Osw
"""

import numpy as np
import matplotlib.pyplot as plt
from numpy.linalg import svd, norm
from scipy.linalg import fractional_matrix_power

# -----------------------------
# 1. Data Generation Functions
# -----------------------------
def generate_low_rank(m, n, r):
    U = np.random.randn(m, r)
    V = np.random.randn(n, r)
    return U @ V.T

def A_forward(A, X):
    return A @ X.flatten()

# -----------------------------
# 2. Regularization Operators
# -----------------------------
def svt(X, tau):
    """ Singular Value Thresholding for NNM and L*-F """
    U, S, Vt = svd(X, full_matrices=False)
    S = np.maximum(S - tau, 0)
    return U @ np.diag(S) @ Vt

def truncated_svt(X, tau, t):
    """ Truncated SVT for Lt,*-F: Protects first t singular values """
    U, S, Vt = svd(X, full_matrices=False)
    # Only shrink singular values from index t onwards
    for i in range(t, len(S)):
        S[i] = max(S[i] - tau, 0)
    return U @ np.diag(S) @ Vt

# -----------------------------
# 3. ADMM Solver
# -----------------------------
def admm_solver(A, y, m, n, lam=0.1, rho=1, t=None, iters=50):
    X = np.zeros((m, n))
    Z = np.zeros((m, n))
    U = np.zeros((m, n))

    # Precompute for X-update efficiency
    AtA = A.T @ A
    I_mn = np.eye(m * n)
    inv_matrix = np.linalg.inv(AtA + rho * I_mn)

    for k in range(iters):
        # X-update (Least Squares)
        rhs = A.T @ y + rho * (Z - U).flatten()
        X_vec = inv_matrix @ rhs
        X = X_vec.reshape(m, n)

        # Z-update (Non-convex Proximal Step)
        if t is None:
            Z = svt(X + U, lam / rho)
        else:
            Z = truncated_svt(X + U, lam / rho, t)

        # Dual-update
        U = U + X - Z

    return X

# -----------------------------
# 4. Main Simulation Loop
# -----------------------------
# Constants based on Algorithm 5.1 and Section 5 of Huang et al.
m, n, r = 30, 30, 5
M = 500
t_rank = 2  # Truncation parameter
sigma_0 = 0.05  # Matrix perturbation Z noise level
noise_levels = np.linspace(0.01, 0.25, 8)

error_nnm = []
error_standard = []
error_truncated = []

for sigma in noise_levels:
    # Generate True Signal
    X_true = generate_low_rank(m, n, r)

    # Generate Completely Perturbed Model components
    A = np.random.randn(M, m*n) / np.sqrt(M)
    Z_noise = sigma_0 * np.random.randn(m, n)
    omega = sigma * np.random.randn(M)

    # Observed y = A(X + Z) + omega
    y = A @ (X_true.flatten() + Z_noise.flatten()) + omega

    # --- WHITENING STEP (Algorithm 5.1) ---
    # Theta and Covariance Sigma
    theta = sigma**2 + (m * n * sigma_0**2) / M
    Sigma = (sigma**2) * np.eye(M) + (sigma_0**2) * (A @ A.T)
    Sigma1 = Sigma / theta

    # Whitening operator: Sigma1^(-1/2)
    W = fractional_matrix_power(Sigma1, -0.5).real

    y_white = W @ y
    A_white = W @ A
    # --------------------------------------

    # Reconstruction
    # 1. NNM (Standard Nuclear Norm - effectively t=0 or lam higher)
    X_nnm = admm_solver(A_white, y_white, m, n, lam=0.1, t=None)

    # 2. L*-F (Difference of Norms)
    X_std = admm_solver(A_white, y_white, m, n, lam=0.2, t=None)

    # 3. Lt,*-F (Truncated Difference)
    X_tru = admm_solver(A_white, y_white, m, n, lam=0.2, t=t_rank)

    # Compute Relative Frobenius Errors
    error_nnm.append(norm(X_nnm - X_true, 'fro') / norm(X_true, 'fro'))
    error_standard.append(norm(X_std - X_true, 'fro') / norm(X_true, 'fro'))
    error_truncated.append(norm(X_tru - X_true, 'fro') / norm(X_true, 'fro'))

# -----------------------------
# 5. Visualization
# -----------------------------
plt.figure(figsize=(10, 6))
plt.plot(noise_levels, error_nnm, 'g^-', label="NNM")
plt.plot(noise_levels, error_standard, 'o-', label="L*-F (Difference)")
plt.plot(noise_levels, error_truncated, 's-', label="Lt,*-F (Truncated)")

plt.xlabel("Measurement Noise Level (sigma)")
plt.ylabel("Relative Recovery Error")
plt.title("Matrix Recovery Comparison under Noise Folding")
plt.legend()
plt.grid(True)
plt.show()